### ISSUE TITLE
accidentally moved twitch chat off screen

### ISSUE THREAD

**Issue by Apoxiosis** [trmcnvn/twitch-chat-overlay#24]
cannot find out how to reset the location of the overlay

**Comment by trmcnvn** [comment]
You'll have to reset your storage settings for Twitch. If you know how to open the dev console in your browser you can run the following JavaScript while visiting https://twitch.tv

```js
window.localStorage.removeItem("tco-ext:settings");
```

**Comment by Apoxiosis** [comment]
i do not know how. can you walk me through it

**Comment by trmcnvn** [comment]
Here's a multi-browser guide on how to open the dev console: https://support.airtable.com/hc/en-us/articles/232313848-How-to-open-the-developer-console

**Comment by trmcnvn** [comment]
Just released an update that won't allow the chat window to be dragged off screen.
